# Generated by Django 5.0.3 on 2024-03-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecArea',
            fields=[
                ('recArea_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('cant_area', models.IntegerField()),
                ('areaTotal_price', models.FloatField()),
                ('area_id', models.IntegerField()),
                ('area_name', models.CharField(max_length=20)),
                ('recArea_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecProduct',
            fields=[
                ('recProduct_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Cant_product', models.IntegerField()),
                ('productTotal_price', models.FloatField()),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=20)),
                ('recProduct_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecRegister',
            fields=[
                ('recRegister_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('cant_register', models.IntegerField()),
                ('registerTotal_price', models.FloatField()),
                ('register_id', models.IntegerField()),
                ('recRegister_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
