# Generated by Django 5.0.3 on 2024-03-30 05:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('area_name', models.CharField(max_length=20)),
                ('area_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=20)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('product_description', models.CharField(max_length=300)),
                ('weight', models.CharField(max_length=20)),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.area')),
            ],
        ),
    ]
