# Generated by Django 5.0.3 on 2024-03-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='cant',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
